# 主成分分析法 PCA [principal Components Analysis]


In [2]:
import numpy as np
X = np.mat([[4,2],[0,2],[-2,0],[-2,-4]])
print(X)

[[ 4  2]
 [ 0  2]
 [-2  0]
 [-2 -4]]


In [3]:
# print(X.T)
print(X.T * X)


[[24 16]
 [16 24]]


In [2]:
tr, W = np.linalg.eig(X.T * X)
print(tr)

[40.  8.]


In [3]:
print(W)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [4]:
w1 = W[:,0].T
print(X * w1.T)

[[ 4.24264069]
 [ 1.41421356]
 [-1.41421356]
 [-4.24264069]]
