In [1]:
import numpy as np

A = np.mat([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
U, sigma, VT = np.linalg.svd(A)

print("U", U)
print("sigma", sigma)
print("VT", VT)

U [[-0.20673589 -0.88915331  0.40824829]
 [-0.51828874 -0.25438183 -0.81649658]
 [-0.82984158  0.38038964  0.40824829]]
sigma [2.54368356e+01 1.72261225e+00 5.14037515e-16]
VT [[-0.40361757 -0.46474413 -0.52587069 -0.58699725]
 [ 0.73286619  0.28984978 -0.15316664 -0.59618305]
 [ 0.44527162 -0.83143156  0.32704826  0.05911168]
 [ 0.3189564  -0.09338934 -0.77009054  0.54452347]]


In [3]:
sigma_c = np.diag(sigma[0:1])
U_c = U[:, 0:1]
VT_c = VT[0:1, :]

print(sigma_c)
print(U_c)
print(VT_c)


[[25.43683563]]
[[-0.20673589]
 [-0.51828874]
 [-0.82984158]]
[[-0.40361757 -0.46474413 -0.52587069 -0.58699725]]


In [4]:
print("conv A", U_c * sigma_c * VT_c)

conv A [[ 2.12250651  2.44395316  2.76539981  3.08684646]
 [ 5.32114289  6.12701254  6.93288219  7.73875183]
 [ 8.51977928  9.81007192 11.10036456 12.3906572 ]]


In [5]:
# 降维
print(A * VT_c.T)
print(U_c * sigma_c)

[[ -5.25870689]
 [-13.18362544]
 [-21.10854399]]
[[ -5.25870689]
 [-13.18362544]
 [-21.10854399]]
